booklist = [("History of England, Foundation","Ackroyd, Peter","197","history"),
("Artist and the Mathematician, The","Aczel, Amir","186","science"),
("False Impressions","Archer, Jeffery","177","fiction"),
("Prisoner of Birth, A","Archer, Jeffery","176","fiction"),
("One","Bach, Richard","172","nonfiction"),
("Mossad","Baz-Zohar, Michael","236","history"),
("Complete Mastermind, The","BBC","178","nonfiction"),
("Men of Mathematics","Bell, E T","217","mathematics"),
("Electric Universe","Bodanis, David","201","science"),
("Learning OpenCV","Bradsky, Gary","232","data_science"),
("To Sir With Love","Braithwaite","197","fiction"),
("Angels & Demons","Brown, Dan","178","fiction"),
("Angels & Demons","Brown, Dan","170","fiction"),
("Outsider, The","Camus, Albert","198","fiction"),
("Tao of Physics, The","Capra, Fritjof","179","science"),
("Hidden Connections, The","Capra, Fritjof","197","science"),
("Uncommon Wisdom","Capra, Fritjof","197","nonfiction"),
("Machine Learning for Hackers","Conway, Drew","233","data_science"),
("Jim Corbett Omnibus","Corbett, Jim","223","nonfiction"),
("Introduction to Algorithms","Cormen, Thomas","234","computer_science"),
("Jurassic Park","Crichton, Michael","174","fiction"),
("Last Mughal, The","Dalrymple, William","199","history"),
("Beyond the Three Seas","Dalrymple, William","197","history"),
("City of Djinns","Dalrymple, William","198","history"),
("Oxford book of Modern Science Writing","Dawkins, Richard","240","science"),
("Beautiful and the Damned, The","Deb, Siddhartha","198","nonfiction"),
("Batatyachi Chal","Deshpande P L","200","fiction"),
("Hafasavnuk","Deshpande P L","211","fiction"),
("Urlasurla","Deshpande P L","211","fiction"),
("Asami Asami","Deshpande, P L","205","fiction"),
("Radiowaril Bhashane & Shrutika","Deshpande, P L","213","nonfiction"),
("Gun Gayin Awadi","Deshpande, P L","212","nonfiction"),
("Aghal Paghal","Deshpande, P L","212","nonfiction"),
("Apulki","Deshpande, P L","211","nonfiction"),
("Char Shabda","Deshpande, P L","214","nonfiction"),
("Vyakti ani Valli","Deshpande, P L","211","nonfiction"),
("Ahe Manohar Tari","Deshpande, Sunita","213","nonfiction"),
("Numbers Behind Numb3rs, The","Devlin, Keith","202","science"),
("Christmas Carol, A","Dickens, Charles","196","fiction"),
("Ropemaker, The","Dickinson, Peter","196","fiction"),
("Crime and Punishment","Dostoevsky, Fyodor","180","fiction"),
("Idiot, The","Dostoevsky, Fyodor","197","fiction"),
("Think Complexity","Downey, Allen","230","data_science"),
("Complete Sherlock Holmes, The - Vol I","Doyle, Arthur Conan","176","fiction"),
("Complete Sherlock Holmes, The - Vol II","Doyle, Arthur Conan","176","fiction"),
("New Markets & Other Essays","Drucker, Peter","176","economics"),
("Age of Discontuinity, The","Drucker, Peter","178","economics"),
("Superfreakonomics","Dubner, Stephen","179","economics"),
("Freakonomics","Dubner, Stephen","197","economics"),
("Pattern Classification","Duda, Hart","241","data_science"),
("Story of Philosophy, The","Durant, Will","170","philosophy"),
("Rosy is My Relative","Durrell, Gerald","176","fiction"),
("Dylan on Dylan","Dylan, Bob","197","nonfiction"),
("Image Processing with MATLAB","Eddins, Steve","241","signal_processing"),
("Age of Wrath, The","Eraly, Abraham","238","history"),
("Surely You're Joking Mr Feynman","Feynman, Richard","198","science"),
("Great War for Civilization, The","Fisk, Robert","197","history"),
("Age of the Warrior, The","Fisk, Robert","197","history"),
("Pillars of the Earth, The","Follett, Ken","176","fiction"),
("Data Smart","Foreman, John","235","data_science"),
("Computer Vision, A Modern Approach","Forsyth, David","255","data_science"),
("Veteran, The","Forsyth, Frederick","177","fiction"),
("Phantom of Manhattan, The","Forsyth, Frederick","180","fiction"),
("Deceiver, The","Forsyth, Frederick","178","fiction"),
("Design with OpAmps","Franco, Sergio","240","computer_science"),
("From Beirut to Jerusalem","Friedman, Thomas","202","history"),
("Case of the Lame Canary, The","Gardner, Earle Stanley","179","fiction"),
("Maqta-e-Ghalib","Garg, Sanjay","221","fiction"),
("Sea of Poppies","Ghosh, Amitav","197","fiction"),
("Information, The","Gleick, James","233","science"),
("Doctor in the Nude","Gordon, Richard","179","fiction"),
("Doctor on the Brain","Gordon, Richard","204","fiction"),
("Fundamentals of Wavelets","Goswami, Jaideva","228","signal_processing"),
("Econometric Analysis","Greene, W. H.","242","economics"),
("Brethren, The","Grisham, John","174","fiction"),
("Soft Computing & Intelligent Systems","Gupta, Madan","242","data_science"),
("Raisin in the Sun, A","Hansberry, Lorraine","175","fiction"),
("Free Will","Harris, Sam","203","philosophy"),
("God Created the Integers","Hawking, Stephen","197","mathematics"),
("Theory of Everything, The","Hawking, Stephen","217","science"),
("Neural Networks","Haykin, Simon","240","data_science"),
("Physics & Philosophy","Heisenberg, Werner","197","science"),
("Catch 22","Heller, Joseph","178","fiction"),
("Farewell to Arms, A","Hemingway, Ernest","179","fiction"),
("Mein Kampf","Hitler, Adolf","212","nonfiction"),
("Hunchback of Notre Dame, The","Hugo, Victor","175","fiction"),
("Clash of Civilizations and Remaking of the World Order","Huntington, Samuel","228","history"),
("Eyeless in Gaza","Huxley, Aldous","180","fiction"),
("Talking Straight","Iacoca, Lee","175","nonfiction"),
("Data Analysis with Open Source Tools","Janert, Phillip","230","data_science"),
("Trial, The","Kafka, Frank","198","fiction"),
("Manasa","Kale, V P","213","nonfiction"),
("Let Us C","Kanetkar, Yashwant","213","computer_science"),
("Pointers in C","Kanetkar, Yashwant","213","computer_science"),
("Arthashastra, The","Kautiyla","214","philosophy"),
("How to Think Like Sherlock Holmes","Konnikova, Maria","240","psychology"),
("O Jerusalem!","Lapierre, Dominique","217","history"),
("City of Joy, The","Lapierre, Dominique","177","fiction"),
("Freedom at Midnight","Lapierre, Dominique","167","history"),
("Girl with the Dragon Tattoo","Larsson, Steig","179","fiction"),
("Girl who kicked the Hornet's Nest","Larsson, Steig","179","fiction"),
("Girl who played with Fire","Larsson, Steig","179","fiction"),
("Prince, The","Machiavelli","173","philosophy"),
("Maugham's Collected Short Stories, Vol 3","Maugham, William S","171","fiction"),
("Ashenden of The British Agent","Maugham, William S","160","fiction"),
("Moon and Sixpence, The","Maugham, William S","180","fiction"),
("Trembling of a Leaf, The","Maugham, William S","205","fiction"),
("Python for Data Analysis","McKinney, Wes","233","data_science"),
("Integration of the Indian States","Menon, V P","217","history"),
("Drunkard's Walk, The","Mlodinow, Leonard","197","science"),
("Power Electronics - Mohan","Mohan, Ned","237","computer_science"),
("Half A Life","Naipaul, V S","196","fiction"),
("In a Free State","Naipaul, V. S.","196","fiction"),
("India's Legal System","Nariman","177","nonfiction"),
("Scoop!","Nayar, Kuldip","216","history"),
("Discovery of India, The","Nehru, Jawaharlal","230","history"),
("Data Mining Handbook","Nisbet, Robert","242","data_science"),
("Making Software","Oram, Andy","232","computer_science"),
("Down and Out in Paris & London","Orwell, George","179","nonfiction"),
("Animal Farm","Orwell, George","180","fiction"),
("We the People","Palkhivala","216","philosophy"),
("We the Nation","Palkhivala","216","philosophy"),
("Last Lecture, The","Pausch, Randy","197","nonfiction"),
("Zen & The Art of Motorcycle Maintenance","Pirsig, Robert","172","philosophy"),
("Tales of Mystery and Imagination","Poe, Edgar Allen","172","fiction"),
("Statistical Decision Theory'","Pratt, John","236","data_science"),
("Return of the Primitive","Rand, Ayn","202","philosophy"),
("We the Living","Rand, Ayn","178","fiction"),
("Ayn Rand Answers","Rand, Ayn","203","philosophy"),
("Philosophy: Who Needs It","Rand, Ayn","171","philosophy"),
("Justice, Judiciary and Democracy","Ranjan, Sudhanshu","224","philosophy"),
("Power Electronics - Rashid","Rashid, Muhammad","235","computer_science"),
("Cathedral and the Bazaar, The","Raymond, Eric","217","computer_science"),
("Tales of Beedle the Bard","Rowling, J K","184","fiction"),
("On Education","Russell, Bertrand","203","philosophy"),
("History of Western Philosophy","Russell, Bertrand","213","philosophy"),
("Unpopular Essays","Russell, Bertrand","198","philosophy"),
("Empire of the Mughal - The Tainted Throne","Rutherford, Alex","180","history"),
("Empire of the Mughal - Brothers at War","Rutherford, Alex","180","history"),
("Empire of the Mughal - Ruler of the World","Rutherford, Alex","180","history"),
("Empire of the Mughal - The Serpent's Tooth","Rutherford, Alex","180","history"),
("Empire of the Mughal - Raiders from the North","Rutherford, Alex","180","history"),
("Broca's Brain","Sagan, Carl","174","science"),
("Orientalism","Said, Edward","197","history"),
("More Tears to Cry","Sassoon, Jean","235","fiction"),
("Data Scientists at Work","Sebastian Gutierrez","230","data_science"),
("Argumentative Indian, The","Sen, Amartya","209","nonfiction"),
("Idea of Justice, The","Sen, Amartya","212","nonfiction"),
("Identity & Violence","Sen, Amartya","219","philosophy"),
("Rationality & Freedom","Sen, Amartya","213","economics"),
("Image Processing & Mathematical Morphology","Shih, Frank","241","signal_processing"),
("Signal and the Noise, The","Silver, Nate","233","data_science"),
("Simpsons & Their Mathematical Secrets","Singh, Simon","233","science"),
("Code Book, The","Singh, Simon","197","science"),
("Wealth of Nations, The","Smith, Adam","175","economics"),
("Courtroom Genius, The","Sorabjee","217","nonfiction"),
("Russian Journal, A","Steinbeck, John","196","nonfiction"),
("Journal of a Novel","Steinbeck, John","196","fiction"),
("Once There Was a War","Steinbeck, John","196","nonfiction"),
("Moon is Down, The","Steinbeck, John","196","fiction"),
("Winter of Our Discontent, The","Steinbeck, John","196","fiction"),
("Burning Bright","Steinbeck, John","175","fiction"),
("Life in Letters, A","Steinbeck, John","196","nonfiction"),
("Grapes of Wrath, The","Steinbeck, John","196","fiction"),
("Textbook of Economic Theory","Stonier, Alfred","242","economics"),
("Amulet of Samarkand, The","Stroud, Jonathan","179","fiction"),
("Structure & Interpretation of Computer Programs","Sussman, Gerald","240","computer_science"),
("Data Structures Using C & C++","Tanenbaum, Andrew","235","computer_science"),
("Analysis, Vol I","Tao, Terence","248","mathematics"),
("Structure and Randomness","Tao, Terence","252","mathematics"),
("Principles of Communication Systems","Taub, Schilling","240","computer_science"),
("India from Midnight to Milennium","Tharoor, Shashi","198","history"),
("Great Indian Novel, The","Tharoor, Shashi","198","fiction"),
("Bookless in Baghdad","Tharoor, Shashi","206","nonfiction"),
("Elements of Information Theory","Thomas, Joy","229","data_science"),
("Nature of Statistical Learning Theory, The","Vapnik, Vladimir","230","data_science"),
("Statistical Learning Theory","Vapnik, Vladimir","228","data_science"),
("Social Choice & Welfare, Vol 39 No. 1","Various","235","economics"),
("20000 Leagues Under the Sea","Verne, Jules","190","fiction"),
("Birth of a Theorem","Villani, Cedric","234","mathematics"),
("Slaughterhouse Five","Vonnegut, Kurt","198","fiction"),
("Short History of the World, A","Wells, H G","197","history"),
("New Machiavelli, The","Wells, H. G.","180","fiction"),
("Devil's Advocate, The","West, Morris","178","fiction"),
("All the President's Men","Woodward, Bob","177","history"),
("Veil: Secret Wars of the CIA","Woodward, Bob","171","history"),
("Dongri to Dubai","Zaidi, Hussain","216","nonfiction")]
